# Generated by Django 4.0.4 on 2022-05-29 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_location_photo_name_photo_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-id']},
        ),
    ]
