# Generated by Django 4.0.4 on 2022-05-29 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_alter_photo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
